### ISSUE TITLE
API GIVE

### ISSUE THREAD

**Issue by ExploitNet** [theofficialvkr/VKRdownloader#17]
Is it possible to send me the main api that is running in vercel?
I can set it up for free on my personal server and provide you with the correct link

**Comment by theofficialvkr** [comment]
Notice: Support Needed to Keep VKrDownloader Alive
Dear VKrDownloader Users,
I'm reaching out to let you know that VKrDownloader has hit the free-tier limit on Vercel, which means they've temporarily suspended my account and the server. Since VKrDownloader is a free tool, covering the costs for premium hosting has become challenging. I want to keep VKrDownloader available to everyone, but without support, it’s difficult to continue.
I’m actively working to find a solution, and I’ll keep you updated. If you appreciate VKrDownloader and find it useful, please consider supporting the project. With your help, I can ensure VKrDownloader stays up and running for everyone to use.
Thank you for your understanding and support!
Best,Vijay Kumar
    On Thursday 24 October, 2024 at 08:12:08 pm IST, ExploitNet ***@***.***> wrote:  
 
 


Is it possible to send me the main api that is running in vercel?
I can set it up for free on my personal server and provide you with the correct link

**Comment by ExploitNet** [comment]
I can support this service using my personal servers. If you want to cooperate, send me an ID on Telegram 
@ImSoheilOfficial
send a message
